title: Niseko Area Mountain Bike Association
description: |
  The Niseko Area Mountain Bike Association (NAMBA) is a nonprofit organization based in Niseko,
  Japan. This volunteer-based, grassroots organization is focused on the building of trails and
  community and is working towards transforming Niseko into Asia's premier mountain bike
  destination. Learn more about us, our trails and the future of mountain biking in Japan at
  NAMBA.ngo
baseurl: ""
url: https://namba.ngo
github_username:  nisekomtb

strict_front_matter: true
permalink: /:categories/:title-:year/

liquid:
  error_mode: strict

defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: en
      og:
        image: /assets/images/og/hero.jpg
  - scope:
      path: ja
    values:
      lang: ja
  - scope:
      path: projects/twin-peaks
    values:
      og:
        image: /assets/images/og/twinpeaks.jpg
  - scope:
      path: ja/projects/twin-peaks
    values:
      og:
        image: /assets/images/og/twinpeaks.jpg
  - scope:
      path: twin-peaks
    values:
      og:
        image: /assets/images/og/twinpeaks-2024.jpg
  - scope:
      path: ja/twin-peaks
    values:
      og:
        image: /assets/images/og/twinpeaks-2024.jpg

include:
  - .well-known
